### ISSUE TITLE
Add an example for setting preprocessor macros

### ISSUE THREAD

**Issue by efarraro** [game-ci/documentation#473]
**Context**

Sometimes you want to include a preprocessor macro in your build (eg: #ANDROID, #DEMO, etc... ) in order to change what gets compiled into the build. Unity supports this behavior in the editor.

**Suggested solution**

Add the following example outlined here as an example in the 'Builder' section of the official wiki: https://github.com/game-ci/unity-builder/issues/207

(Credit to @xwipeoutx for posting the following solution)
```yaml
steps:
  - name: Apply csc.rsp (pre-processor symbols)
    run: echo -define:MY_SYMBOL >> Assets/csc.rsp
```

You will get warnings about "unapplied changes" - you could get around this by putting `csc.rsp` in your `.gitignore`, or allowing dirty build.

```yaml
with:
  # ...
  allowDirtyBuild: true
```

Now in your code you can just do this:
```c
void Start() {
#if MY_SYMBOL
  GetComponent<TMP_Text>().text = "I have a symbol!";
#else
  GetComponent<TMP_Text>().text = "I do not have a symbol...";
#endif
}
```

See [Unity docs](https://docs.unity3d.com/Manual/CustomScriptingSymbols.html) for the inspiration - under the heading "Setting scripting symbols via an asset file"

_Originally posted by @xwipeoutx in https://github.com/game-ci/unity-builder/issues/207#issuecomment-2269981553_
