### ISSUE TITLE
Multiple private Github repositories: "Prepare SSH config for unity builder" fails

### ISSUE THREAD

**Issue by brianzaubar** [game-ci/documentation#482]
**Bug description**

I am following [these](https://game.ci/docs/github/builder/#multiple-private-github-repositories) steps.
The git action fails at the "Prepare SSH config for unity builder" step with this error:
```
cp: cannot stat '/home/runner/.ssh/known_hosts': No such file or directory
Error: Process completed with exit code 1.
```

**Steps to reproduce**

I added 3 different public SSH key for three different private repositories under my organization (No write access).
These are my Git Action steps:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: |
            ${{ secrets.FIRST_SSH_KEY }}
            ${{ secrets.SECOND_SSH_KEY }}
            ${{ secrets.THIRD_SSH_KEY }}
      
      - name: Prepare SSH config for unity builder
        run: |
          mkdir $HOME/.ssh_docker
          cp $HOME/.ssh/config $HOME/.ssh_docker/
          cp $HOME/.ssh/key* $HOME/.ssh_docker/
          cp $HOME/.ssh/known_hosts $HOME/.ssh_docker/
          sed -i 's/\/home\/runner/\/root/g' $HOME/.ssh_docker/config
          sudo chown -R root:root $HOME/.ssh_docker
          GIT_CONFIG_EXTENSIONS=$(git config --list | grep '^url\.')
          {
            echo 'GIT_CONFIG_EXTENSIONS<<EOF'
            echo "$GIT_CONFIG_EXTENSIONS"
            echo EOF
          } >> "$GITHUB_ENV"
        shell: bash
      
      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          sshAgent: ${{ env.SSH_AUTH_SOCK }}
          sshPublicKeysDirectoryPath: ${{ env.HOME }}/.ssh_docker
          targetPlatform: WebGL
          customParameters: "${{ inputs.development-build && '-Development -AllowDebugging' }}"

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
```

**Expected behavior**

Finish SSH config for Unity Builder

**Comment by GabLeRoux** [comment]
I asked ChatGPT and it came up wit this:

---

You're encountering an error during the "Prepare SSH config for unity builder" step in your GitHub Actions workflow:

```
cp: cannot stat '/home/runner/.ssh/known_hosts': No such file or directory
Error: Process completed with exit code 1.
```

This error indicates that the `known_hosts` file is missing, which is essential for SSH to verify the authenticity of the hosts you're connecting to. To resolve this issue, you can create the `known_hosts` file before attempting to copy it. Here's how you can modify your workflow:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          docker: false
          homebrew: false
          dotnet: false
          android: false
          misc: false

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts
        shell: bash

      - name: Prepare SSH config for unity builder
        run: |
          cp -R ~/.ssh /home/runner/
        shell: bash

      - name: Build with Unity
        uses: game-ci/unity-builder@v4
        with:
          targetPlatform: StandaloneWindows64
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
```

**Explanation:**

1. **Set up SSH**: This step ensures that the `.ssh` directory and the `known_hosts` file exist. It then adds GitHub's SSH key to the `known_hosts` file to prevent SSH from prompting for verification during the build process.

2. **Prepare SSH config for unity builder**: This step copies the `.ssh` directory to the `/home/runner/` directory, making the SSH configuration available for subsequent steps.

By creating the `known_hosts` file and adding GitHub's SSH key, you should resolve the error and allow your workflow to proceed without issues.

---

Might be worth giving a try. If it works, let's update our docs too 🙏
